### ISSUE TITLE
aisdls in trainers not defined

### ISSUE THREAD

**Issue by KaDnt** [CIA-Oceanix/TrAISformer#3]
trAISformer.py fails with:

Loading ./data/ct_dma/ct_dma_train.pkl...
10605 9144
Length: 9144
Creating pytorch dataset...
Loading ./data/ct_dma/ct_dma_valid.pkl...
1481 1291
Length: 1291
Creating pytorch dataset...
Loading ./data/ct_dma/ct_dma_test.pkl...
1593 1453
Length: 1453
Creating pytorch dataset...
2022-01-10 15:42:56,974 - models - number of parameters: 5.742055e+07
epoch 1 iter 285: loss 4.83882. lr 5.993205e-04: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 286/286 [00:43<00:00,  6.52it/s]
2022-01-10 15:43:43,212 - root - Training, epoch 1, loss 9.46821, lr 5.993205e-04.
2022-01-10 15:43:45,291 - root - Valid, epoch 1, loss 4.55070.
2022-01-10 15:43:45,298 - root - Best epoch: 001, saving model to ./results/ct_dma-pos-pos_vicinity-10-40-blur-True-False-2-1.0-data_size-250-270-30-72-embd_size-256-256-128-128-head-8-8-bs-32-lr-0.0006-seqlen-18-120/model.pt
Traceback (most recent call last):
  File "/rhenus/w4/donandt/TrAISformer/trAISformer.py", line 122, in <module>
    trainer.train()
  File "/rhenus/w4/donandt/TrAISformer/trainers.py", line 279, in train
    seqs, masks, seqlens, mmsis, time_starts =  iter(aisdls["test"]).next()
NameError: name 'aisdls' is not defined

**Comment by KaDnt** [comment]
I have just noticed that this problem has already been reported in an already closed issue. However, the problem continues to exist. I have added my suggestions to the closed issue.
